apiVersion: v1
kind: Service
metadata:
  name: sms-service
  namespace: sms-namespace
spec:
  selector:
    app: sms
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
      nodePort: 30007
  type: NodePort
